### ISSUE TITLE
spurious error for font-weight

### ISSUE THREAD

**Issue by wkeese** [carbon-design-system/stylelint-plugin-carbon-tokens#103]
Given the SCSS of

```scss
@use "@carbon/type";
...
.keyword,
.function {
  font-weight: type.font-weight("semibold");
}

```

I'm getting the error that:

```
✖  Expected carbon type token, mixin or function for "font-weight" found "type.font-weight("semibold")".  carbon/type-token-use
```

Presumably, that shouldn't be flagged, because `type.font-weight()` **is** a carbon mixin.
