### ISSUE TITLE
indirect styles for padding (or anything?) rejected

### ISSUE THREAD

**Issue by wkeese** [carbon-design-system/stylelint-plugin-carbon-tokens#106]
This works fine with no lint errors:

```scss
.foo {
  padding: spacing.$spacing-04 spacing.$spacing-05;
}
```

However, this fails:

```scss
$container-padding: spacing.$spacing-04 spacing.$spacing-05;
.foo {
  padding: $container-padding;
}
```

Is it possible to support both (without throwing an error)?
