### ISSUE TITLE
Spurious warnings about motion token uses

### ISSUE THREAD

**Issue by wkeese** [carbon-design-system/stylelint-plugin-carbon-tokens#127]
Given SCSS like:

```scss
@use "@carbon/motion" as motion;

.foo {
    transition: opacity motion.$duration-fast-02;
}
```

I get the spurious carbon/motion-duration-use error that:

> ✖  Expected carbon motion token, mixin or function to be set for variable "motion.$duration-fast-02" used by            
>            "transition" found "an unknown, undefined or unrecognized value".

(AFAICT I *am* using a carbon motion token.)

Possibly this is related to still being on Carbon 10.  We are in the process of upgrading to Carbon 11, but I haven't checked there yet.  I remember there being something weird about the number of dashes changing, like $duration--fast-02 --> $duration-fast-02, or vice-versa.
